language: node_js
node_js:
  - '8'
install:
  - npm i
before_script:
  - echo "Asia/Shanghai" | sudo tee /etc/timezone
  - sudo dpkg-reconfigure -f noninteractive tzdata
script:
  - npm run ci
after_script:
  - npm i codecov && codecov
